task-5: add interface Saver
ozonva/ova-conversation-api pull request #5
Opened 2021-08-25 13:58 UTC by Hudmot

Задание V:
Нужно в пакете saver имплементировать Saver интерфейс, с возможностью писать в хранилище данные, через Flusher, сброс данных происходит во flusher по определенному таймауту или при вызове метода Close
package saver

```
type Saver interface {
	Save(entity models.Entity) // заменить на свою сущность
    // Init()
	Close()
}
```

```
// NewSaver возвращает Saver с поддержкой переодического сохранения
func NewSaver(
	capacity uint,
	flusher flusher.Flusher,
  // ...
) Saver {
  // ...
}
```
До сброса в хранилище, данные хранятся в slice. который принадлежит saver-у.
Установка capacity данного slice-a идет на этапе конструирование -  при вызове NewSaver

2021-08-29 20:35 UTC, dk13danger requested changes

2021-08-29 20:35 UTC, dk13danger commented on internal/saver/saver.go
> +	"ova-conversation-api/internal/domain"
Не стал в прошлый раз писать, т.к. не хотелось из-за этого правки вносить. Но тут напишу: обычно принято разделять пустой строкой импорты:
```
stg packages (e.g. fmt, context, net/http, etc..)
// empty string
3-rd party packages + internal project packages
```

2021-08-29 20:35 UTC, dk13danger commented on internal/saver/saver.go
> +	Init()
Вообще, этот метод закомментирован в задании (может там ошибка)

2021-08-29 20:35 UTC, dk13danger commented on internal/saver/saver.go
> +	wg.Wait()
У тебя тут зависнет метод Init()

2021-08-29 20:35 UTC, dk13danger commented on internal/saver/saver.go
> +	if (cap(s.data) == 0) || (len(s.data) == cap(s.data)-1) {
Вообще немного перемудрил. Можно просто сделать массив из моделей и проверять его на входной `capacity`. Если он переполнился - то сразу очищать его

2021-08-29 20:35 UTC, dk13danger commented on internal/saver/saver.go
> +	s.data = append(s.data, entity)
Это же можно было и 1 раз написать?

2021-08-30 14:43 UTC, Hudmot commented on internal/saver/saver.go
> +	"ova-conversation-api/internal/domain"
поправил

2021-08-30 14:45 UTC, Hudmot commented on internal/saver/saver.go
> +	Init()
Убрал из интерфейса, сделал `init() ` закрытым

2021-08-30 14:48 UTC, Hudmot commented on internal/saver/saver.go
> +	wg.Wait()
Убрал WaitGroup (использовалось для отладки)

2021-09-05 19:50 UTC, dk13danger approved these changes

2021-09-05 19:50 UTC, merged